apiVersion: apps/v1
kind: Deployment
metadata:
  name: slokamtech
  labels:
    app: slokamtech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slokamtech
  template:
    metadata:
      labels:
        app: slokamtech
    spec:
      containers:
      - name: slokamtech
        image: 8329557283/dockerdeptest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: slokamtech
  labels:
    app: slokamtech
spec:
  selector:
    app: slokamtech
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
